// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_8Xtuk6o3IWhxysnkl0YGuLzM30DJeW0',
    appId: '1:515992855793:web:706062cec84dd694427550',
    messagingSenderId: '515992855793',
    projectId: 'uptech-ee8fe',
    authDomain: 'uptech-ee8fe.firebaseapp.com',
    databaseURL: 'https://uptech-ee8fe-default-rtdb.firebaseio.com',
    storageBucket: 'uptech-ee8fe.appspot.com',
    measurementId: 'G-T0DCV7MPL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjJ4KpaKIsC0QD4rgxVeSTuM8n-sdYPWo',
    appId: '1:515992855793:android:6ac6c2ed54fe668a427550',
    messagingSenderId: '515992855793',
    projectId: 'uptech-ee8fe',
    databaseURL: 'https://uptech-ee8fe-default-rtdb.firebaseio.com',
    storageBucket: 'uptech-ee8fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfg9nI3S0opiLgvutuoYXFAcd5r3WrKkk',
    appId: '1:515992855793:ios:abe41db47e27abf9427550',
    messagingSenderId: '515992855793',
    projectId: 'uptech-ee8fe',
    databaseURL: 'https://uptech-ee8fe-default-rtdb.firebaseio.com',
    storageBucket: 'uptech-ee8fe.appspot.com',
    iosClientId: '515992855793-b0pbnh29rrvke1c670ehcoln3u31nn7p.apps.googleusercontent.com',
    iosBundleId: 'com.htnguyen.uptech.uptech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfg9nI3S0opiLgvutuoYXFAcd5r3WrKkk',
    appId: '1:515992855793:ios:d6665f765e8ce756427550',
    messagingSenderId: '515992855793',
    projectId: 'uptech-ee8fe',
    databaseURL: 'https://uptech-ee8fe-default-rtdb.firebaseio.com',
    storageBucket: 'uptech-ee8fe.appspot.com',
    iosClientId: '515992855793-r94bgethvs7f07kinus24d3pk26imknl.apps.googleusercontent.com',
    iosBundleId: 'com.htnguyen.uptech.uptech.RunnerTests',
  );
}
